sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

env:
  - DEPS=lowest
  - DEPS=highest

install:
  - if [ "$DEPS" = "lowest" ]; then
      composer update -n --prefer-source --prefer-lowest;
    else
      composer update -n --prefer-source;
    fi;
  - composer show

script:
  - $(php -r 'if (PHP_MAJOR_VERSION >= 7) echo "phpdbg -qrr"; else echo "php";') vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
  - php vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_script:
  - composer require satooshi/php-coveralls dev-master
  - php vendor/bin/coveralls -v

cache:
  directories:
    - $HOME/.composer/cache
