sudo: false

language: php

php:
  - 7.0
  - nightly

before_script:
  - composer self-update
  - composer require satooshi/php-coveralls:dev-master
  - composer install

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
  - php vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_script:
  - php vendor/bin/coveralls -v

cache:
  directories:
    - $HOME/.composer/cache
